export const flagCurrensies: Record<string, string> = {
  // Fiat
  USD: "🇺🇸", 
  EUR: "🇪🇺", 
  GBP: "🇬🇧", 
  JPY: "🇯🇵", 
  AUD: "🇦🇺", 
  CAD: "🇨🇦", 
  CHF: "🇨🇭", 
  CNY: "🇨🇳", 
  SEK: "🇸🇪", 
  NZD: "🇳🇿", 
  NOK: "🇳🇴", 
  DKK: "🇩🇰", 
  PLN: "🇵🇱", 
  CZK: "🇨🇿", 
  HUF: "🇭🇺", 
  INR: "🇮🇳", 
  BRL: "🇧🇷", 
  MXN: "🇲🇽", 
  ZAR: "🇿🇦", 
  TRY: "🇹🇷", 
  RUB: "🇷🇺", 
  UAH: "🇺🇦", 

  // Cripto
  BTC: "₿",   
  ETH: "Ξ",   
  LTC: "Ł",   
  XRP: "✕",   
  DOGE: "🐶", 
  SOL: "◎",   
  DOT: "●",   
  ADA: "🅐",  
  BNB: "🟡", 
  USDT: "₮", 
  USDC: "Ⓤ", 
};